default: &default
    adapter: postgresql
    username: postgres
    password: postgres
    host: localhost
    port: 5432

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test
  
production:
   <<: *default
   adapter: postgresql
   database: db_production
